### ISSUE TITLE
Add option to omit semicolon

### ISSUE THREAD

**Issue by rwaltenberg** [NuclleaR/vscode-extension-auto-import#1]
Standard ESLint gives an error for unnecessary semicolons at the end of the line. It would be great if there's an option to omit them.

**Comment by JesseChrestler** [comment]
aren't those es-lint errors fixable? --fix where it will automatically remove those? I know that doesn't help when the plugin doesn't configure this, but that might be a stop gap for the interim.

**Comment by rwaltenberg** [comment]
@JesseChrestler, that's actually a great stop gap! But I hope the option gets implemented.

It's true that it can be automatically fixed but will still get validation highlights if ESLint plugin is installed on VSCode. `eslint.autoFixOnSave` can be set but the highlights will still be there until save.

**Comment by Lxxyx** [comment]
this is helpful. I do not use eslint.

**Comment by Miskamyasa** [comment]
+

**Comment by pungggi** [comment]
exactly what I need too, would the maintainer consider a PR for this?

**Comment by andy-viv** [comment]
FWIW I opened a PR for this option (#15)
