### ISSUE TITLE
【BUG】import with es6 default export should not in brace.

### ISSUE THREAD

**Issue by Lxxyx** [NuclleaR/vscode-extension-auto-import#3]
1. I write this code:

![image](https://user-images.githubusercontent.com/13161470/31584264-2297aac6-b171-11e7-84b0-ab47da73b27b.png)

2. In another file, auto import suggestion is error:

![image](https://user-images.githubusercontent.com/13161470/31584276-487471ca-b171-11e7-92d1-1e93eca12849.png)

![image](https://user-images.githubusercontent.com/13161470/31584285-4d52eeb0-b171-11e7-85ae-451dc3934b2d.png)

**Comment by maibono** [comment]
I too am facing this issue for importing a Icon module in my React JS code for the following import
`import Icon  from '@material-ui/core/Icon';`
this plugin is importing with braces which is causing bugs
`import { Icon } from '@material-ui/core/Icon';`

Any suggestions or is there an alternative plugin to solve this issue

**Comment by alexandrsek** [comment]
Same problem. Any solutions to this?
